# Generated by Django 4.2.23 on 2025-07-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('temp_config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member_of_groups', models.JSONField(blank=True, default=list)),
                ('can_create_app', models.BooleanField(default=False)),
                ('can_configure_these_apps', models.JSONField(blank=True, default=list)),
                ('can_view_these_apps', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_eppn', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_email', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('advisors_and_readers', models.CharField(blank=True, max_length=255, null=True)),
                ('team_members', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_mentors', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('research_program', models.CharField(blank=True, max_length=255, null=True)),
                ('license_options', models.CharField(blank=True, max_length=100, null=True)),
                ('visibility_options', models.CharField(blank=True, max_length=100, null=True)),
                ('concentrations', models.CharField(blank=True, max_length=255, null=True)),
                ('degrees', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_file', models.FileField(blank=True, null=True, upload_to='primary_files/')),
                ('supplementary_files', models.FileField(blank=True, null=True, upload_to='supplementary_files/')),
                ('original_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staged_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('checksum_type', models.CharField(blank=True, max_length=100, null=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('temp_submission_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ready_to_ingest', 'Ready to Ingest'), ('ingested', 'Ingested'), ('ingest_error', 'Ingestion Error')], default='created', max_length=100)),
                ('staff_ingester', models.CharField(blank=True, max_length=100, null=True)),
                ('ingest_error_message', models.TextField(blank=True, null=True)),
                ('bdr_pid', models.CharField(blank=True, max_length=20, null=True, verbose_name='BDR PID')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bdr_uploader_hub_app.appconfig')),
            ],
        ),
    ]
