# Generated by Django 4.2.23 on 2025-07-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdr_uploader_hub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
