# Generated by Django 5.2.13 on 2026-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdr_uploader_hub_app', '0003_submission_target_collection_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
